2.7

diff --git a/.github/workflows/_SOT.yml b/.github/workflows/_SOT.yml
--- a/.github/workflows/_SOT.yml
+++ b/.github/workflows/_SOT.yml
@@ -112,57 +112,57 @@ jobs:
         git checkout test
         git merge develop
 
-    - name: Configure cache and ccache
-      run: |
-        # docker start paddle-CI /bin/bash
-        # docker exec -it paddle-CI
-        mkdir -p /home/data/cfs/.cache/build
-        echo "CACHE_DIR=/home/data/cfs/.cache/build" >> $GITHUB_ENV
-        if [ -f '/home/data/gzcfs/gz.txt' ];then
-          mkdir -p /home/data/gzcfs/.ccache/sot
-          echo "CCACHE_DIR=/home/data/gzcfs/.ccache/sot" >> $GITHUB_ENV
-        else
-          mkdir -p /home/data/cfs/.ccache/sot
-          echo "CCACHE_DIR=/home/data/cfs/.ccache/sot" >> $GITHUB_ENV
-        fi
+    # - name: Configure cache and ccache
+    #   run: |
+    #     # docker start paddle-CI /bin/bash
+    #     # docker exec -it paddle-CI
+    #     mkdir -p /home/data/cfs/.cache/build
+    #     echo "CACHE_DIR=/home/data/cfs/.cache/build" >> $GITHUB_ENV
+    #     if [ -f '/home/data/gzcfs/gz.txt' ];then
+    #       mkdir -p /home/data/gzcfs/.ccache/sot
+    #       echo "CCACHE_DIR=/home/data/gzcfs/.ccache/sot" >> $GITHUB_ENV
+    #     else
+    #       mkdir -p /home/data/cfs/.ccache/sot
+    #       echo "CCACHE_DIR=/home/data/cfs/.ccache/sot" >> $GITHUB_ENV
+    #     fi
 
-    - name: Check sot
-      env:
-        work_dir: "/workspace/Paddle"
-        PADDLE_ROOT: "/workspace/Paddle"
-      continue-on-error: true
-      run: |
-        # docker start paddle-CI /bin/bash
-        # docker exec -it paddle-CI
-        EXCODE=0
-        # set +e
-        PATH=/usr/local/bin:${PATH}
-        ln -sf $(which python3.10) /usr/local/bin/python
-        ln -sf $(which pip3.10) /usr/local/bin/pip
-        bash -x ${work_dir}/paddle/scripts/paddle_build.sh cicheck_sot;EXCODE=$?
-        echo "EXCODE=$EXCODE" >> $GITHUB_ENV
+    # - name: Check sot
+    #   env:
+    #     work_dir: "/workspace/Paddle"
+    #     PADDLE_ROOT: "/workspace/Paddle"
+    #   continue-on-error: true
+    #   run: |
+    #     # docker start paddle-CI /bin/bash
+    #     # docker exec -it paddle-CI
+    #     EXCODE=0
+    #     # set +e
+    #     PATH=/usr/local/bin:${PATH}
+    #     ln -sf $(which python3.10) /usr/local/bin/python
+    #     ln -sf $(which pip3.10) /usr/local/bin/pip
+    #     bash -x ${work_dir}/paddle/scripts/paddle_build.sh cicheck_sot;EXCODE=$?
+    #     echo "EXCODE=$EXCODE" >> $GITHUB_ENV
 
-    - name: Check result
-      run: |
-        # docker start paddle-CI /bin/bash
-        # docker exec -it paddle-CI
-        if [[ $EXCODE -eq 0 ]];then
-          echo "Congratulations!  Your PR passed the paddle-build."
-        elif [[ $EXCODE -eq 4 ]];then
-          echo "Sorry, your code style check failed."
-        elif [[ $EXCODE -eq 5 ]];then
-          echo "Sorry, API's example code check failed."
-        elif [[ $EXCODE -eq 6 ]];then
-          echo "Sorry, your pr need to be approved."
-        elif [[ $EXCODE -eq 7 ]];then
-          echo "Sorry, build failed."
-        elif [[ $EXCODE -eq 8 ]];then
-          echo "Sorry, some tests failed."
-        elif [[ $EXCODE -eq 9 ]];then
-          echo "Sorry, coverage check failed."
-        fi
-        # set -x
-        exit $EXCODE
+    # - name: Check result
+    #   run: |
+    #     # docker start paddle-CI /bin/bash
+    #     # docker exec -it paddle-CI
+    #     if [[ $EXCODE -eq 0 ]];then
+    #       echo "Congratulations!  Your PR passed the paddle-build."
+    #     elif [[ $EXCODE -eq 4 ]];then
+    #       echo "Sorry, your code style check failed."
+    #     elif [[ $EXCODE -eq 5 ]];then
+    #       echo "Sorry, API's example code check failed."
+    #     elif [[ $EXCODE -eq 6 ]];then
+    #       echo "Sorry, your pr need to be approved."
+    #     elif [[ $EXCODE -eq 7 ]];then
+    #       echo "Sorry, build failed."
+    #     elif [[ $EXCODE -eq 8 ]];then
+    #       echo "Sorry, some tests failed."
+    #     elif [[ $EXCODE -eq 9 ]];then
+    #       echo "Sorry, coverage check failed."
+    #     fi
+    #     # set -x
+    #     exit $EXCODE
 
     # - name: Terminate and delete the container
     #   if: always()
