test=document_fix

diff --git a/.github/workflows/CheckPRTemplate.yml b/.github/workflows/CheckPRTemplate.yml
--- a/.github/workflows/CheckPRTemplate.yml
+++ b/.github/workflows/CheckPRTemplate.yml
@@ -20,49 +20,49 @@ jobs:
         path: ~/.cache/pip
         key: checkpr_pip
 
-    - name: Get commit message
-        id: get_commit_message
-        run: |
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV
+    # - name: Get commit message
+    #     id: get_commit_message
+    #     run: |
+    #       COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+    #       echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV
 
-    - name: Do check
-      env:
-        AGILE_PULL_ID: ${{ github.event.pull_request.number }}
-        GITHUB_API_TOKEN: ${{ secrets.PADDLE_GITHUB_API_TOKEN }}
-        AGILE_COMPILE_BRANCH: develop
-        AGILE_CHECKIN_AUTHOR: ${{ github.event.pull_request.user.login }}
-        AGILE_REVISION: ${{ github.event.pull_request.head.sha }}
-        AGILE_COMMENTS: "[{\"commit\": $AGILE_REVISION, \"author\": $AGILE_CHECKIN_AUTHOR, \"comment\": ${{ env.commit_message }}}]"
-        icafe_url: ${{ secrets.icafe_url }}
-        icafe_user: ${{ secrets.icafe_user }}
-        icafe_pwd: ${{ secrets.icafe_pwd }}
-        db_host: ${{ secrets.db_host }}
-        db_port: ${{ secrets.db_port }}
-        db_user: ${{ secrets.db_user }}
-        db_pd: ${{ secrets.db_pd }}
-        db_name: ${{ secrets.db_name }}
-        method: check_pr
-      run: |
-        echo $GITHUB_API_TOKEN
-        git checkout -b test
-        pip install httpx pymysql PyGithub
-        python tools/CheckPRTemplate.py;EXCODE=$?
-        echo "EXCODE: $EXCODE"
-        echo "ipipe_log_param_EXCODE: $EXCODE"
-        set +x
-        if [[ "$EXCODE" != "0" ]];then
-        echo -e "######################################################"
-        echo -e "If you encounter a situation where the PR template does not match the error message, please use the following link to update your PR: [  https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/.github/PULL_REQUEST_TEMPLATE.md ]"
-        echo -e "##ReferenceDocumentation: ##"
-        echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/PULL-REQUEST-TEMPLATE--REFERENCE ]"
-        echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/paddle_ci_manual ]"
-        echo -e "######################################################"
-        fi
+    # - name: Do check
+    #   env:
+    #     AGILE_PULL_ID: ${{ github.event.pull_request.number }}
+    #     GITHUB_API_TOKEN: ${{ secrets.PADDLE_GITHUB_API_TOKEN }}
+    #     AGILE_COMPILE_BRANCH: develop
+    #     AGILE_CHECKIN_AUTHOR: ${{ github.event.pull_request.user.login }}
+    #     AGILE_REVISION: ${{ github.event.pull_request.head.sha }}
+    #     AGILE_COMMENTS: "[{\"commit\": $AGILE_REVISION, \"author\": $AGILE_CHECKIN_AUTHOR, \"comment\": ${{ env.commit_message }}}]"
+    #     icafe_url: ${{ secrets.icafe_url }}
+    #     icafe_user: ${{ secrets.icafe_user }}
+    #     icafe_pwd: ${{ secrets.icafe_pwd }}
+    #     db_host: ${{ secrets.db_host }}
+    #     db_port: ${{ secrets.db_port }}
+    #     db_user: ${{ secrets.db_user }}
+    #     db_pd: ${{ secrets.db_pd }}
+    #     db_name: ${{ secrets.db_name }}
+    #     method: check_pr
+    #   run: |
+    #     echo $GITHUB_API_TOKEN
+    #     git checkout -b test
+    #     pip install httpx pymysql PyGithub
+    #     python tools/CheckPRTemplate.py;EXCODE=$?
+    #     echo "EXCODE: $EXCODE"
+    #     echo "ipipe_log_param_EXCODE: $EXCODE"
+    #     set +x
+    #     if [[ "$EXCODE" != "0" ]];then
+    #     echo -e "######################################################"
+    #     echo -e "If you encounter a situation where the PR template does not match the error message, please use the following link to update your PR: [  https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/.github/PULL_REQUEST_TEMPLATE.md ]"
+    #     echo -e "##ReferenceDocumentation: ##"
+    #     echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/PULL-REQUEST-TEMPLATE--REFERENCE ]"
+    #     echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/paddle_ci_manual ]"
+    #     echo -e "######################################################"
+    #     fi
 
-        [[ $EXCODE -eq 0 ]] && {
-        set +x
-        wget -q --no-check-certificate  https://paddle-qa.bj.bcebos.com/baidu/cloud/modify_icafe.py
-        set -x
-        python3 modify_icafe.py
-        }
+    #     [[ $EXCODE -eq 0 ]] && {
+    #     set +x
+    #     wget -q --no-check-certificate  https://paddle-qa.bj.bcebos.com/baidu/cloud/modify_icafe.py
+    #     set -x
+    #     python3 modify_icafe.py
+    #     }
